### ISSUE TITLE
Does it work with Varnish 6? How to install it on Jelastic? 

### ISSUE THREAD

**Issue by MtDalPizzol** [nytimes/libvmod-queryfilter#5]
I'm new to Varnish and I'm using it on Jelastic. I followed [this tutorial](https://docs.jelastic.com/varnish) to get things working, but there's little to none info on VMODs.

First of all: does this module work with Varnish 6?

It seems I need a `libvmod_queryfilter.so` file. So I need to SSH, clone it on the server and build it there? Or can I build it locally an then upload only the `.so` file to the server?

**Comment by andrew-canaday** [comment]
Hey @MtDalPizzol, sorry for the delayed response here.

The present `master` version of libvmod-queryfilter requires the common method of:
 * Download Varnish source code
 * Build varnish from source
 * Download the VMOD source code
 * Point the VMOD at the _built_ varnish source using an environment variable
 * Compiling the vmod and installing it

An example (for a different vmod) [can be found here](http://blog.jambura.com/2014/09/28/building-a-varnish-vmod/).

The [1.0-prerelease branch](https://github.com/nytimes/libvmod-queryfilter/tree/1.0-prerelease) _does_ allow you to build the VMOD _without having to build varnish_ if you are able to install a `varnish-dev` or `varnish-devel` type package on your system.

Unfortunately, this effort got lost in the shuffle of other high priority work and fell by the wayside. I'll see if I can get some time allocated to wrap the release up and add support for 6, as well.

Hysterically, the unfinished v1.0 supports 3, 4, and 5 - but hasn't been updated for 6 (this doesn't mean it _won't_ work - just that it hasn't been tested).

**Comment by andrew-canaday** [comment]
Version `1.0.0` now officially includes Varnish 6 support.
Unfortunately, I can't provide any guidance regarding Jelastic.

Closing this out. Please feel free to open another if you run into issues with Varnish 6 compatibility/building.
