### ISSUE TITLE
Incorrect separator when arrays_enabled is false

### ISSUE THREAD

**Issue by swla** [nytimes/libvmod-queryfilter#6]
If arrays_enabled is false, the separator is not set to '&' after the first parameter unless the first parameter is a flag. The block at lines 261-263 in vmod_queryfilter.c must be moved below the setting of the separator at line 272.

**Comment by andrew-canaday** [comment]
Oh! This is a great catch! Thank you, @swla!

**Comment by swla** [comment]
Happy to help :)

**Comment by stankolubomir** [comment]
Could we know the state of this issue? We just ran into this problem. We will use enabled arrays, but it could be great to fix this because arrays are not always needed in query parameters.

**Comment by ghost** [comment]
Hey, @stankolubomir there should be a working version in [this branch](https://github.com/nytimes/libvmod-queryfilter/tree/issue-6).

The only thing holding up the merge / release is _unit tests_ for the above branch.
Contributions are welcome, if you feel inclined! Else, I'll get the tests done and the release cut by end of next week, latest.

_Sincerest apologies_ for the holdup. Truly.

**Comment by andrew-canaday** [comment]
(Just wanted to reassure: this didn't fall by the wayside. On it. Will post back and close when the release is cut).

**Comment by ghost** [comment]
@swla / @stankolubomir, this should be fixed. I'll be cutting a new release today [diff here](https://github.com/nytimes/libvmod-queryfilter/compare/master..issue-6-empty-params).

I ran into some dev complications and subsequently discovered a related bug.

Some temporary docker-based tests are now in place to get around the dev limitations I ran into (also provides some scaffolding for implementing CI for this module in the near future).

Apologies for the holdup. Thanks for hanging in.

**Comment by ghost** [comment]
**[v1.0.1](https://github.com/nytimes/libvmod-queryfilter/releases/tag/v1.0.1)** is released!

Going to close. Please feel free to re-open if the issue persists.
